- name: Variables on play level
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print Variable
      debug:
        msg: URL = {{URL}}
    ## In Ansible we access variables in two flower braces

    - name: Print Variable from Task Declaration
      vars:
        URL: task.google.com
      debug:
        msg: URL = {{URL}}
    ## NOTE: Task level variables overides the play level variables

- name: Declare Variable in a file and Access it
  hosts: all
  vars_files:
    - vars01.yml
  tasks:
    - name: Print variable from files
      debug:
        msg: URL = {{URL}}

- name: Declare Variable from Inventory file
  hosts: all
  tasks:
    - name: Print Variable from inventory
      debug:
        msg: URL = {{URL}}

- name: Prompt for the variable
  hosts: all
  vars_prompt:
    - name: URL
      prompt: Enter URL
      private: no
  tasks:
    - name: Print from prompt
      debug:
        msg: URL = {{URL}}

- name: Register Variables
  hosts: all
  tasks:
    - name: Find files
      find:
        paths: /boot
      register: OUTPUT

    - name: Print OUTPUT
      debug:
        msg: OUTPUT = {{OUTPUT}}


#- name: Variable precedence
#  hosts: all
#  vars:
#    URL: play.example.com
#    vars_files:
#      - vars01.yml
#  vars_prompt:
#    - name: URL
#      prompt: Enter URL
#      private: no
#  tasks:
#    - name: Print Variable
#      debug:
#        msg: URL = {{URL}}
#      vars:
#        URL: task.example.com

## Observations,
## vars, vars_files, inventory, tasks
## Lower the number higher the priority
# 0. Command line arguments given as -e VAR=DATA
# 1. tasks
#### Roles variables take precedence when you use roles.
# 2. vars_files
# 3. vars_prompt
# 4. vars
# 5. Inventory



